site_name: Internal All The Things (中文版)
site_description: '内网渗透与 Active Directory 实战攻防速查表 (中文翻译版)'
site_url: https://n00o00b.github.io/InternalAllTheThings_CN/

repo_url: https://github.com/n00o00b/InternalAllTheThings_CN
edit_uri: blob/main/docs/

theme:
  name: material
  custom_dir: overrides
  color_mode: auto
  user_color_mode_toggle: true
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.tracking
    - navigation.top
    - search.share
    - search.suggest

extra_css:
  - custom.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - i18n:
      languages:
        - locale: zh
          name: 中文
          default: true
          build: true
        - locale: en
          name: English
          build: true
      fallback_to_default: true
  - search
  - git-revision-date-localized
  - social